language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

services:
  - postgresql

addons:
    postgresql: "9.6"

before_script:
  - psql -c 'create database shoden_test;' -U postgres

env:
  global:
    - DATABASE_URL=postgres://localhost:5432/shoden_test
